### ISSUE TITLE
Missing `Version.h` header file

### ISSUE THREAD

**Issue by MatejKafka** [Matrix4f/Binary-IO#1]
Multiple files in the project depend on a `Version.h` file (`#include "Version.h"`), which is not present in the project.

**Comment by SohamGovande** [comment]
Thanks for bringing this issue to my attention. You can create a very simple `Version.h` file with a single struct, as follows, to let the program compile correctly:

`struct Version { unsigned char major; unsigned short minor; unsigned char patch; }`
